apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi.fullname" . }}-web
  labels:
  {{- include "jitsi.labels" . | nindent 4 }}
spec:
  ports:
  - name: "http"
    port: {{ .Values.service.port }}
    targetPort: 80
  - name: "https"
    port: 443
    targetPort: 443
  selector:
    {{- include "jitsi.selectorLabels" . | nindent 4 }}
